Add filelist buffer
supersaintex/super-commit.nvim pull request #4
Opened 2024-10-15 18:18 UTC by KKuze

## Summary:
- Added a window that lists the paths of files with changes.
- Implemented a feature to display the diff when the Enter key is pressed on a file path.
- Revised parts of the previous code structure in accordance with the above changes.
## How to Confirm:
- Run nvim test.super in the project's root directory.
## Issues:
- Specifically, I am uncertain about the method of passing the file paths obtained in `filepath/get.lua` to `window.lua` through `keymap.lua`. Is this approach appropriate?

2024-10-16 05:25 UTC, manhatsu requested changes

2024-10-16 05:25 UTC, manhatsu commented on lua/super-commit/git/commands.lua
> +commands[2] = "echo select a file under window"
```suggestion
commands[2] = "echo select a file name from above"
```

2024-10-16 07:36 UTC, asana17 requested changes
Partial review, I will add some comments later.

2024-10-16 07:36 UTC, asana17 commented on lua/super-commit/keymap.lua
> +end
You are just using this function when setting the keymap. The function itself does not include anything related to `enter`, `normalmode`, and even `nvim_set_keymap()`.

The function name should be something that represents its contents, such as `show_file_diff()`.

2024-10-16 07:43 UTC, asana17 commented
Please make the scope clear.

Also, don't ask question in the PR description. You need to make it clear before making PR, or scope out from the PR.

2024-10-16 08:04 UTC, asana17 requested changes

2024-10-16 08:04 UTC, asana17 commented on lua/super-commit/window.lua
> +      local commands = git_cmds.commands
```suggestion
      local command_table = git_cmds.commands
```
Name variables consistently.

2024-10-16 08:13 UTC, asana17 requested changes
Please make the commit message more understandable.

For example:
`chore: rename test.super to execute auto commands`
↓
```
chore: rename test.txt to test.super to trigger autocmd

The autocmds defined in the init module are triggered with "*.super".
```

2024-10-16 08:13 UTC, asana17 commented on lua/super-commit/window/open.lua
>    return bufnum_table
This return is not necessary because the bufnum table is now accessible from `M.bufnums`.

2024-10-16 08:22 UTC, asana17 commented on lua/super-commit/window.lua
> +      vim.api.nvim_set_keymap(
I agree with this. If you put these series of functions outside, the code will be clearer.

2024-10-16 08:24 UTC, asana17 commented on lua/super-commit/git/commands.lua
> +commands[2] = "echo select a file under window"
Probably this command is not necessary.

2024-10-16 12:36 UTC, seiay commented on lua/super-commit/git/commands.lua
> +commands[4] = "git diff --name-only --cached"
I guessed that the index of the commands table matched the buffer number.
It was a little confusing.

Should we manage the commands and buffer number tables in a <key, value> type?
For example, keys indicate the position of the window.

2024-10-16 12:50 UTC, KKuze commented on lua/super-commit/git/commands.lua
> +  return M.show_command_output(bufnum, "git diff --cached ".. path)
Fixed it in 98748433df82d574429ec9f1a9cc04f0e8cea997.

2024-10-16 13:37 UTC, asana17 commented on lua/super-commit/git/commands.lua
> +function M.show_diff_cmd_output(bufnum, path)
Solved. This is now implemented in `show_command_output()`.

2024-10-16 15:42 UTC, KKuze commented on lua/super-commit/git/commands.lua
> +commands[2] = "echo select a file under window"
Fixed in 952ca594e5953c6ff37fe484860f75fa69143528.

2024-10-16 15:43 UTC, KKuze commented on lua/super-commit/window.lua
> +      vim.api.nvim_set_keymap(
Fix it in the next pr.

2024-10-16 16:14 UTC, KKuze commented on lua/super-commit/filepath/get.lua
> +end
Fixed in 706684b265fcea4b854bbed68ee7008f4b9b548e.

2024-10-17 11:13 UTC, KKuze commented on lua/super-commit/keymap.lua
> +end
Fixed in 4cfaaed041ce188002cb201b9f45605b267aed26.

2024-10-17 12:57 UTC, asana17 commented on lua/super-commit/keymap.lua
> +end
Is the dedicated `keymap` module necessary?
Again, this is just a function to show file diff, not related to keymap.
You can put this function in the `git` or `window` modules.

2024-10-17 12:59 UTC, asana17 commented on lua/super-commit/git/commands.lua
> +commands[2] = "echo select a file under window"
The message is still unclear.
`To show git diff of files, select the file path in the window below, and press Enter.`

2024-10-17 13:42 UTC, KKuze commented on lua/super-commit/keymap.lua
> +end
keymapをwindow.luaに移す

2024-10-17 13:53 UTC, asana17 commented on lua/super-commit/window/open.lua
>    return bufnum_table
Why do you need to return `M.bufnums` in this function, even though `M.bufnums` is accessible when you load the module?

2024-10-18 18:32 UTC, KKuze commented on lua/super-commit/window.lua
> +      local commands = git_cmds.commands
Fixed in d6019e61631eea4948376d76d80b44c8aff49116.

2024-10-18 18:48 UTC, KKuze commented on lua/super-commit/window/open.lua
>    return bufnum_table
Fixed in 8285a57b63d244cb07f2da4dd52187e8d9f54cee.

2024-10-18 18:49 UTC, KKuze commented on lua/super-commit/keymap.lua
> +end
Refactored it in 416fd932b11e54be09a9f867b7fa6c2915787e74.

2024-10-18 18:50 UTC, KKuze commented on lua/super-commit/git/commands.lua
> +commands[2] = "echo select a file under window"
Fixed it in 8285a57b63d244cb07f2da4dd52187e8d9f54cee.

2024-10-19 01:54 UTC, seiay commented on lua/super-commit/window.lua
> +          [[<Cmd>lua require('super-commit/keymap').enter_in_normalmode()<CR>]],
@KKuze You seem to forget this.

2024-10-19 03:58 UTC, asana17 commented on lua/super-commit/window/open.lua
> +  M.bufnums = bufnum_table
This was fixed in 8285a57b63d244cb07f2da4dd52187e8d9f54cee.

2024-10-19 03:59 UTC, asana17 commented on lua/super-commit/window.lua
> +          [[<Cmd>lua require('super-commit/keymap').enter_in_normalmode()<CR>]],
We can leave this now. Thank you for the reminder, @manhatsu .

2024-10-19 05:21 UTC, asana17 commented on lua/super-commit/window.lua
> +      local commands = git_cmds.commands
This is not mandatory and we can fix it in a different PR.

2024-10-19 05:22 UTC, asana17 commented
Please squash the fixup commit after resolving the discussion [here](https://github.com/supersaintex/super-commit.nvim/pull/4#discussion_r1802513752).
I will then approve this PR.

2024-10-19 06:35 UTC, KKuze commented on lua/super-commit/keymap.lua
> +end
Please merge the branch as is.

2024-10-19 06:43 UTC, KKuze commented on lua/super-commit/keymap.lua
> +end
Fixed it c00091611c30c815fb7da1d991a2e41df4e280c7.
Renamed function to show_selected_diff.

2024-10-19 08:23 UTC, asana17 requested changes
We have some more fixes necessary.

2024-10-19 08:23 UTC, asana17 commented on lua/super-commit/filepath/get.lua
This implementation is deleted in the next commit because we have the corresponding Nvim API.
Please apply that solution in this commit too.

Or you can probably drop this commit and put `nvim_set_keymap()` in the next commit.

2024-10-19 08:23 UTC, asana17 commented on lua/super-commit/super-commit.lua
> +
This change is not related to the commit title `chore: rename file from window.lua to super-commit.lua`.

2024-10-19 08:23 UTC, asana17 commented on lua/super-commit/git/commands.lua
> +local explanation = "To show git diff of files, select the file path in the window below, and press Enter."
Make variable names more descriptive. 
For example:
```suggestion
local diff_keymap_msg = "To show git diff of files, select the file path in the window below, and press Enter."
```

2024-10-19 08:23 UTC, asana17 commented on lua/super-commit/git/keymap.lua
> +return M
We discussed that this `setup()` function is unrelated to `keymap` and it is moved into another module by the next commit.
Implement this directly in the other module.

2024-10-19 08:31 UTC, asana17 commented
Can you move this 6a95a7b92e1d5ba9d1ae2ad26af7130611ee39be before the commits that adding main features?

2024-10-20 12:08 UTC, asana17 requested changes

2024-10-20 12:15 UTC, asana17 commented on lua/super-commit/filepath/get.lua
This is solved.

2024-10-20 12:16 UTC, asana17 commented on lua/super-commit/super-commit.lua
> +
This is solved.

2024-10-21 14:18 UTC, asana17 commented on lua/super-commit/git/commands.lua
> +local explanation = "To show git diff of files, select the file path in the window below, and press Enter."
This is solved.

2024-10-21 14:59 UTC, asana17 commented on lua/super-commit/git/keymap.lua
> +return M
This is solved.

2024-10-21 15:00 UTC, asana17 commented on lua/super-commit/git/commands.lua
> +local commands = {}
This is solved.

2024-10-21 15:00 UTC, asana17 approved these changes
LGTM, thank you for the fix.

2024-10-21 15:12 UTC, manhatsu approved these changes

2024-10-21 15:12 UTC, merged