refactor: manage window numbers, buffer numbers, and commands  in public table
supersaintex/super-commit.nvim pull request #5
Opened 2024-10-21 15:04 UTC by seiay

I checked this plugin behavior didn't change after refactoring.

2024-10-21 15:58 UTC, asana17 requested changes

2024-10-21 15:58 UTC, asana17 commented on lua/super-commit/super-commit.lua
> +      git_cmds.show_command_output_v2(win_manage_table["git-diff-init"])
Here `win_manage_table` is contained in the `git_cmds` module. So you only need to pass keys for these functions:
```suggestion
      git_cmds.show_command_output_v2("git-status")
      git_cmds.show_command_output_v2("filelist")
      git_cmds.show_command_output_v2("git-diff-init")
```

2024-10-21 15:58 UTC, asana17 commented on lua/super-commit/super-commit.lua
> +        win_manage_table["git-diff-init"].buf_num,
Maybe you can move this `show_selected_diff()` into `git/commands.lua`.

2024-10-21 15:58 UTC, asana17 commented on lua/super-commit/git/commands.lua
> +M.win_manage_table = {}
The variable name should be modified.
The table name is `win_manage_table`, but it manages other things, such as `buf_num` and `command`.
Also, it is obvious that the table manages something.

2024-10-21 15:58 UTC, asana17 commented on lua/super-commit/git/commands.lua
> +M.win_manage_table["git-diff-init"] = {win_num=nil, buf_num=nil, command=git_diff_init_msg}
`echo ...` is not a `msg`, it's a command.

```suggestion
local git_diff_init_msg = "To show git diff of files, select the file path in the window below, and press Enter."
M.win_manage_table["git-diff-init"] = {win_num=nil, buf_num=nil, command="echo " .. git_diff_init_msg}
```

2024-10-21 15:58 UTC, asana17 commented on lua/super-commit/git/commands.lua
> +-- M.win_manage_table["commit-msg"] = {win_num=nil, buf_num=nil}
Remove unnecessary implementation instead of commenting it out.

2024-10-21 15:58 UTC, asana17 commented on lua/super-commit/git/commands.lua
> +function M.show_command_output_v2(gitcmd)
Is this `v2()` necessary? You can easily do the same thing using the original one.
```
M.show_command_output(gitcmd.buf_num, gitcmd.command)
```

2024-10-21 15:58 UTC, asana17 commented on lua/super-commit/window/open.lua
> +  win_manage_table["test-win"].buf_num =  vim.api.nvim_get_current_buf();
If we create the table this way, we have to add the `win_manage_table` prefix every time accessing the content inside.
I prefer managing the table for each attribute and access like the below, but you can choose whether to do this:
```
buf_num["test-win"] = ...
win_num["test-win"] = ...
```

FYI, we can create a class-like table instead: we can prepare the `git command` object with members, such as `buf_num`, `win_num`.

2024-10-21 15:58 UTC, asana17 commented on lua/super-commit/window/open.lua
> +  win_manage_table["git-diff-init"].win_num =  vim.api.nvim_win_get_number(0);
These functions are repeated several times.
How about creating a new wrapper function and setting the key as an argument?

2024-10-21 15:58 UTC, asana17 commented on lua/super-commit/window/open.lua
>    vim.cmd('enew')
These commands are also specific to each git command.
We can put these on the `win_manage_table` too.

2024-10-24 04:33 UTC, manhatsu commented on lua/super-commit/super-commit.lua
> +  git_cmds.show_output(map_table["git-diff-init"].bufnum, map_table["git-diff-init"].command)
Improve readability by holding command keys in a set.

`init_commands` can be also used when setting winnum and bufnum, therefore it may be better to define this in `window/open.lua`. 

```suggestion
local init_commands = {"git-status", "filelist", "git-diff-init"}

-- or
-- local init_commands = window_open.init_commands
-- if defined in window/open.lua

function M.init()
  window_open.setup()
  for k in init_commands do
    wn, bn, cm = map_table[k]
    git_cmds.show_output(bn, cm)
```

2024-10-24 04:33 UTC, manhatsu commented on lua/super-commit/window/open.lua
> +  map_table["git-diff-init"].winnum =  vim.api.nvim_win_get_number(0);
Define this routine process outside.
And as I commented in `super-commit.lua`, holding initial command keys in a set improves readability.

```suggestion
function M.set_current_num(key)
  map_table[key].bufnum = vim.api.nvim_get_current_buf();
  map_table[key].winnum = vim.api.nvim_win_get_number(0);
 end
```

2024-10-24 04:52 UTC, asana17 commented on lua/super-commit/git/commands.lua
> +M.map_table["git-diff-init"] = {winnum=nil, bufnum=nil, command="echo " .. file_select_suggestion}
This window is also used to show the diff results.
```suggestion
M.map_table["diff"] = {winnum=nil, bufnum=nil, command="echo " .. file_select_suggestion}
```

2024-10-24 04:54 UTC, asana17 commented on lua/super-commit/git/commands.lua
> +M.win_manage_table["git-diff-init"] = {win_num=nil, buf_num=nil, command=git_diff_init_msg}
This is fixed.

2024-10-24 04:55 UTC, asana17 commented on lua/super-commit/git/commands.lua
> +-- M.win_manage_table["commit-msg"] = {win_num=nil, buf_num=nil}
This is fixed.

2024-10-24 04:57 UTC, asana17 commented on lua/super-commit/git/commands.lua
> +function M.show_command_output_v2(gitcmd)
`v2()` is now deleted.

2024-10-24 04:59 UTC, asana17 commented on lua/super-commit/super-commit.lua
> +  git_cmds.show_output(map_table["git-diff-init"].bufnum, map_table["git-diff-init"].command)
Thank you for providing code examples. 
(Same comment from me, please resolve this at the same time: https://github.com/supersaintex/super-commit.nvim/pull/5#discussion_r1809076684)

2024-10-24 13:23 UTC, seiay commented on lua/super-commit/window/open.lua
> +  win_manage_table["git-diff-init"].win_num =  vim.api.nvim_win_get_number(0);
fixed it in 6a4516906557693fe691f461f14d13833237fb49
I made the Get_win_buf_number() function in window/open.lua.

2024-10-24 14:40 UTC, seiay commented on lua/super-commit/super-commit.lua
> +  git_cmds.show_output(map_table["git-diff-init"].bufnum, map_table["git-diff-init"].command)
Fixed it in 3189900d61664541177854465639614cf10efd0a

2024-10-24 14:45 UTC, seiay commented on lua/super-commit/window/open.lua
> +  map_table["git-diff-init"].winnum =  vim.api.nvim_win_get_number(0);
Fixed it in https://github.com/supersaintex/super-commit.nvim/commit/3189900d61664541177854465639614cf10efd0a

2024-10-25 13:08 UTC, seiay commented on lua/super-commit/window/open.lua
>    vim.cmd('enew')
We will do this in a different PR.

2024-10-25 13:33 UTC, seiay commented on lua/super-commit/super-commit.lua
> +        win_manage_table["git-diff-init"].buf_num,
Fixed it in 58468bbc143d815fe46b4a7bdbb207e5ccf89821

2024-10-25 13:34 UTC, seiay commented on lua/super-commit/git/commands.lua
> +M.map_table["git-diff-init"] = {winnum=nil, bufnum=nil, command="echo " .. file_select_suggestion}
Fixed it in 58468bbc143d815fe46b4a7bdbb207e5ccf89821

2024-10-25 14:10 UTC, seiay commented on lua/super-commit/super-commit.lua
> +      git_cmds.show_command_output_v2(win_manage_table["git-diff-init"])
Thank you for your suggestion.　I think it is better.
We will make the tables easier to access in the future.

2024-10-25 14:17 UTC, seiay commented on lua/super-commit/git/commands.lua
> +M.map_table = {}
How about `public_table`?

(This table may be unused when updating the table definition.)

2024-10-25 14:20 UTC, seiay commented on lua/super-commit/window/open.lua
> +  map_table["git-diff-init"].winnum =  vim.api.nvim_win_get_number(0);
Fixed it in 3189900d61664541177854465639614cf10efd0a

2024-10-25 17:30 UTC, KKuze commented on lua/super-commit/git/commands.lua
> +M.map_table["git-status"] = {winnum=nil, bufnum=nil, command="git status"}
It would be easier to understand if you could fix it below.

```
M.map_table["status"] = {
    winnum=nil,
    bufnum=nil,
    command="git status"
}
M.map_table["filelist"] = {
    winnum=nil,
    bufnum=nil,
    command="git diff --name-only --cached"
}
```

2024-10-26 00:05 UTC, manhatsu commented on lua/super-commit/git/commands.lua
> +M.map_table = {}
I'll leave it to you.

As you say, we don't have to consider very much about this any more, since we'll not use this table in the next update.

2024-10-26 00:07 UTC, manhatsu approved these changes

2024-10-26 00:11 UTC, asana17 commented on lua/super-commit/git/commands.lua
> +M.win_manage_table = {}
This table will be deleted in the future PR. Resoving.

2024-10-26 00:13 UTC, asana17 commented on lua/super-commit/git/commands.lua
> +M.map_table["git-status"] = {winnum=nil, bufnum=nil, command="git status"}
It depends on the developer's preference, but personally I agree with @KKuze.

We can leave this for now.

2024-10-26 00:22 UTC, asana17 commented on lua/super-commit/git/commands.lua
> +M.map_table = {}
I don't think so. The table name should be more descriptive.

This will be fixed in the future commit.

2024-10-26 00:43 UTC, asana17 requested changes
Several small fixes are needed, but looks good to me.
I will approve after you fix them.

2024-10-26 00:43 UTC, asana17 commented on lua/super-commit/super-commit.lua
> +
Adding newline here looks OK, but if it's not intended, delete it.

2024-10-26 00:43 UTC, asana17 commented on lua/super-commit/super-commit.lua
> +--local init_commands = {"git-status", "filelist", "git-diff-init"}
The comment is added here but this is soon deleted by the next commit.

2024-10-26 00:43 UTC, asana17 commented on lua/super-commit/git/commands.lua
> +M.map_table["filelist"] = {winnum=nil, bufnum=nil, command="git diff --name-only --cached"}
It is not mandatory but we can use the same variable name with [Nvim API doc](https://neovim.io/doc/user/api.html).

You can close this comment without any fix.

2024-10-26 00:43 UTC, asana17 commented on lua/super-commit/git/commands.lua
> +M.map_table["status"] = {winnum=nil, bufnum=nil, command="git status"}
These renames are not related to this commit.
Moreover, you can fix these directly in the previous commit.

2024-10-26 00:53 UTC, seiay commented on lua/super-commit/super-commit.lua
> +
I added a line here for readability.

2024-10-26 01:34 UTC, seiay commented on lua/super-commit/super-commit.lua
> +--local init_commands = {"git-status", "filelist", "git-diff-init"}
Fixed it in f58a68fc0d7ee0f86ce3bc61aaf59fac7feffa55

2024-10-26 01:35 UTC, seiay commented on lua/super-commit/git/commands.lua
> +M.map_table["status"] = {winnum=nil, bufnum=nil, command="git status"}
Fixed it in f58a68fc0d7ee0f86ce3bc61aaf59fac7feffa55

2024-10-26 01:41 UTC, seiay commented on lua/super-commit/git/commands.lua
> +M.map_table["filelist"] = {winnum=nil, bufnum=nil, command="git diff --name-only --cached"}
I agree with you.

> You can close this comment without any fix.
Ok!

2024-10-26 03:17 UTC, asana17 approved these changes
LGTM.

2024-10-26 03:29 UTC, merged