Refactor: Module splitting
supersaintex/super-commit.nvim pull request #7
Opened 2024-11-01 12:46 UTC by seiay

2024-11-01 13:32 UTC, asana17 commented
Could you write a short description of this?

2024-11-01 13:47 UTC, asana17 commented
Overall, please split commits more carefully. For example, `refactor: split map_table into tables in each module and make
show_init("key")` has two splittable changes inside.

2024-11-01 14:25 UTC, asana17 requested changes
There are some major points to fix.
I will do another review after these points are fixed.

2024-11-01 14:25 UTC, asana17 commented on lua/super-commit/window/open.lua
> +  M.id["filelist"] = vim.api.nvim_get_current_win()
What about using "key" as an argument for the same initial function?

```suggestion
  function M.setup()
    init("diff")
    init("status")
    init("filelist")
```

```
local win_cmds = {
  diff = {
    "rightbelow split",
    "wincmd l",
  },
  status = {
    "wincmd h",
    "rightbelow split",
    "wincmd j",
  },
  filelist = {
    "wincmd l",
    "rightbelow split",
    "wincmd j",
  },
}

local function init(key)
  for _,v in win_cmd[key] do
    vim.cmd(v)
  end
  M.id[key] = vim.api.nvim_get_current_win()
end
end
```

2024-11-01 14:25 UTC, asana17 commented on lua/super-commit/super-commit.lua
> +local buffer_open = require('super-commit/buffer/open')
Why are these `window/open` and `buffer/open` written in `**/open.lua`?
We can use `window.lua` and `buffer.lua`.

2024-11-01 14:25 UTC, asana17 commented on lua/super-commit/git/commands.lua
> +local buf_ids = require('super-commit/buffer/open').id
The [Nvim API doc](https://neovim.io/doc/user/index.html) has `winid` and `buffer` for corresponding objects (handles), but it does not have `win_id` and `buf_id`. 
I think it is OK to use `buf_id` here to make it clearer than using `buffer`. However, it may be better to write a comment on this.

2024-11-01 14:25 UTC, asana17 commented on lua/super-commit/buffer/open.lua
> +M.id = {}
To be consistent, use the same variable name as possible.

This also applies to `win_ids`.

```suggestion
M.ids = {}
```

2024-11-01 14:25 UTC, asana17 commented on lua/super-commit/git/commands.lua
Is this merge necessary?  If we do this, we can no longer use `M.show_output()` for other commands.

2024-11-01 14:25 UTC, asana17 commented on lua/super-commit/buffer/open.lua
> +M.number = {}
Could you try to make this table local? If it is not a scope, please write it in the PR description instead.

2024-11-03 09:27 UTC, seiay commented on lua/super-commit/super-commit.lua
> +local buffer_open = require('super-commit/buffer/open')
Do you mean we had better write super-commit/window.lua and super-commit/buffer.lua, not using window, buffer directories?

2024-11-03 10:32 UTC, seiay commented on lua/super-commit/buffer/open.lua
> +M.id = {}
Fixed it in ddaa0930d9a1d4ae025fa1a69c6d3fdddb1a7324

2024-11-03 10:35 UTC, seiay commented on lua/super-commit/git/commands.lua
I canceled this merge in 678a9190989a388099704fa192389722f31e872d

2024-11-03 13:26 UTC, asana17 commented on lua/super-commit/super-commit.lua
> +local buffer_open = require('super-commit/buffer/open')
I don't mean we **must** move `open.lua`s to `window.lua` and `buffer.lua`. Sorry for bothering you.

I recommend you to add those addi tional workaround at the time they become necessary.

For now, we can just replace `open.lua`s. This means placing in `open.lua` is just adding extra suffix, and unnecessary.

Suppose the reviwers without any context see these `open.lua`s.
Don't you think they find them strange?

2024-11-03 14:34 UTC, seiay commented on lua/super-commit/buffer/open.lua
> +M.number = {}
Fixed it in cd747304ca9551b8ac8430dcd897df2dc3cf9456

2024-11-03 14:36 UTC, seiay commented on lua/super-commit/window/open.lua
> +  M.id["filelist"] = vim.api.nvim_get_current_win()
Thank you for your suggestion.
I modified it in 2ed21f97bed00595f6bc59b5e6f715600a5c40b7

2024-11-04 03:39 UTC, asana17 commented on lua/super-commit/buffer/open.lua
> +M.number = {}
```
local bufids = require('super-commit/super-commit').bufids
```
Everytime you do this, it is generating new `bufids` instance, instead of referencing the same instance.
Since it is `local`, you can not use it in other place or share the change of values.

2024-11-04 04:05 UTC, asana17 commented on lua/super-commit/buffer/open.lua
> +M.number = {}
Imagine the C files existng, such as`sub.c` which is used in `main.c`. You are now trying to include `main.c` into `sub.c` to use tables in `main.c`.

2024-11-04 10:37 UTC, seiay commented on lua/super-commit/git/commands.lua
> +local buf_ids = require('super-commit/buffer/open').id
I decided to use `winid` like [Nvim API doc](https://neovim.io/doc/user/index.html).

As you commented, I used `bufid`(changed from `buf_id`) because it seemed clearer than `buffer`.

2024-11-04 13:52 UTC, asana17 commented
This PR will be closed to split the scope.

2024-11-04 13:52 UTC, closed without merging