feat: add floating window
supersaintex/super-commit.nvim pull request #9
Opened 2024-11-05 14:24 UTC by KKuze

you can start-up foating window to keydown ctrl-h in '*.super'

2024-11-06 05:19 UTC, asana17 commented
I think you should create appropriate help message instead of usikg temporary messages such as `aaaaa`.

Please fix it, I will review this PR after the fix.

2024-11-06 05:37 UTC, asana17 requested changes

2024-11-06 05:37 UTC, asana17 commented on lua/super-commit/window/float.lua
> +    local msglen = 0;
```suggestion
    local max_len = 0;
```

2024-11-06 05:37 UTC, asana17 commented on lua/super-commit/window/float.lua
> +    local width = screen_width >= 160 and math.floor(screen_width / 2) or msglen
Here you are updating the width based on the editor size, despite the previous implementation calculates the max length of help strings.

Probably the previous calculation of strings are unnecessary.

2024-11-06 05:40 UTC, asana17 commented
Also, the current implementation is good for showing help floating window, but it is difficult to use the implementation for other floating windows.

2024-11-06 14:49 UTC, manhatsu commented on lua/super-commit/window/float.lua
> +    msglen = msglen <= 80 and msglen or 80
It's better to define fixed values (such as `80` or `160`) as local variables if you are going to use them multiple times.

2024-11-06 17:59 UTC, KKuze commented on lua/super-commit/window/float.lua
> +    local msglen = 0;
Fixed it.

2024-11-06 18:16 UTC, KKuze commented on lua/super-commit/window/float.lua
> +    local width = screen_width >= 160 and math.floor(screen_width / 2) or msglen
Fixed as `local max_width = math.floor(screen_width * 2 / 3)`.

2024-11-06 18:19 UTC, KKuze commented on lua/super-commit/window/float.lua
> +    msglen = msglen <= 80 and msglen or 80
The numbers are deleted for the above fix.

2024-11-07 01:10 UTC, asana17 requested changes

2024-11-07 01:10 UTC, asana17 commented on lua/super-commit/window/float.lua
> +                or max_width
For the maximum length, fixed 80 characters are enough for the readability. Thinking of some margin, set a larger fixed size. Don't forget to check whether it is centralized.

Also for the small editor witdh, I suggest to use its full length.

The actual problem occurs when the editor size is small. This implementation still shrinks the floating window sized based on editor width.

Suppose the window editor width equals to "40". Don't you think utilizing the whole window is better than using 2/3?

2024-11-07 01:10 UTC, asana17 commented on lua/super-commit/window/float.lua
> +      col = (screen_width - width) / 2,
Is floor division unnecessary here?

2024-11-07 04:43 UTC, asana17 commented on lua/super-commit/window/float.lua
> +    msglen = msglen <= 80 and msglen or 80
I think `160` still remains in the code. These magic numbers are better to defined as another variable to make the code clearer.

See this [Stack Overflow Q&A](https://stackoverflow.com/questions/47882/what-are-magic-numbers-and-why-do-some-consider-them-bad)

2024-11-07 10:05 UTC, manhatsu commented on lua/super-commit/window/float.lua
> +                or max_width
I agree with this.
And considering the meaning, use `min_width` instead of `max_width`.

2024-11-07 13:11 UTC, manhatsu commented on lua/super-commit/window/float.lua
> +                or max_width
```suggestion
    local max_width = 80 -- or any
    local width = math.min(screen_width, max_width)
```

2024-11-07 14:07 UTC, asana17 requested changes

2024-11-07 14:07 UTC, asana17 commented on .luacheckrc
> +  "string"
`string` is not used anymore.

2024-11-07 14:12 UTC, KKuze commented on .luacheckrc
> +  "string"
Fixed it in 219b40b43c2596f5984d95db27a7910f2b0ff9c2.

2024-11-07 14:18 UTC, KKuze commented on lua/super-commit/window/float.lua
> +    local width = screen_width >= 160 and math.floor(screen_width / 2) or msglen
Fixed it.

2024-11-07 14:18 UTC, KKuze commented on lua/super-commit/window/float.lua
> +    msglen = msglen <= 80 and msglen or 80
Fixed it.

2024-11-07 14:18 UTC, KKuze commented on lua/super-commit/window/float.lua
> +    }
Fixed it.

2024-11-07 14:22 UTC, KKuze commented on lua/super-commit/window/float.lua
> +                or max_width
Fixed It as const value.

2024-11-07 14:23 UTC, KKuze commented on lua/super-commit/window/float.lua
> +      col = (screen_width - width) / 2,
Fixed It as const value.

2024-11-07 15:14 UTC, merged